notifications:
  email: false

git:
  depth: false
  quiet: true

language: java
jdk: oraclejdk8
node_js: lts/*

addons:
  apt:
    packages:
      - bash
      - curl
      - tree
      - jq
      - python-pip

env:
  global:
    - TERM=dumb

install: true
before_install:
  - sudo apt-get update -yqq
  #- sudo pip install docker-compose httpie >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 8080 80

script:
  - ./mvnw -U
  - java -jar ./app/target/*.jar

after_script:
  - stop_any ${KAFKA_PORT} ${ZOOKEEPER_PORT}
